import * as dotenv from 'dotenv';
dotenv.config();
const { APP_PORT, DB_HOST, DB_NAME, JWT_SECRET, APP_SOCKET_CORS_URL, FIREBASE_APIKEY, FIREBASE_AUTHDOMAIN, FIREBASE_PROJECTID, FIREBASE_STORAGEBUCKET, FIREBASE_MESSAGEINGSENDERID, FIREBASE_APPID, FIREBASE_MEASUREMENTID }: any = process.env;

export const ENV = { ...process.env, ...{ APP_PORT, DB_HOST, DB_NAME, JWT_SECRET, APP_SOCKET_CORS_URL } }
export const FIREBASE = { ...process.env, ...{ FIREBASE_APIKEY, FIREBASE_AUTHDOMAIN, FIREBASE_PROJECTID, FIREBASE_STORAGEBUCKET, FIREBASE_MESSAGEINGSENDERID, FIREBASE_APPID, FIREBASE_MEASUREMENTID } }